spring:
  datasource:
    url: jdbc:h2:file:./h2/webasefront_mq;DB_CLOSE_ON_EXIT=FALSE
    databaseName: db
    driverClassName: org.h2.Driver
    serverName:
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      session:
        events:
          log: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username:
    password:
    virtual-host:
    ssl:
      enabled: false

rabbitmq:
  queue:
    service-name: mq_webase
    queue-names: block_exchange.block_queue_1 # 根据db中注册的front名字，动态配置队列名字

server:
  port: 5008
  context-path: /WeBASE-MQ

logging:
  config: classpath:log4j2.xml

constant:
  frontUrl: http://%1s:%2d/WeBASE-Front/%3s
  httpTimeOut: 5000
  contractDeployTimeOut: 30000
  isPrivateKeyEncrypt: true
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000
  mq-server: 127.0.0.1 # 注册queue的服务器地址

